Repository octokit/dotnet-sdk, pull requests merged in 2023-12, with the labels that each got.

#5 Adds and updates repo docs
  Docs/CODE_OF_CONDUCT.md
  Docs/CONTRIBUTING.md
  Docs/RELEASES.md
  Docs/SECURITY.md
  README.md
Labels: documentation

#8 Removes unnecessary filters from ignore
  .gitignore
Labels: maintenance

#10 Removes release and log filters
  .gitignore
Labels: maintenance

#14 Adds trimming props
  src/Octokit.NET.SDK.csproj
Labels: feature

#15 maint: Add editorconfig and perform some code clean up
  .editorconfig
  .gitignore
  GitHub.Octokit.sln
  src/Authentication/TokenAuthenticationProvider.cs
  src/Client/ClientFactory.cs
  src/Client/RequestAdapter.cs
  src/Middleware/APIVersionHandler.cs
  src/Middleware/Options/APIVersionOptions.cs
  src/Middleware/Options/UserAgentOptions.cs
  src/Middleware/UserAgentHandler.cs
  src/Octokit.NET.SDK.csproj
Labels: Type: Maintenance

#18 maint: Update README.md
  README.md
Labels: Type: Maintenance

#19 maint: adds templates for PR and issue dev flows
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/maintenance.yml
  .github/pull_request_template.md
Labels: Type: Maintenance

#16 feat: adds strong name key and modifies workflows to sign assemblies
  .github/workflows/build.yml
  .github/workflows/publish.yml
  key.snk
Labels: Type: Feature

#21 Adds NuGetVersion property to csproj for packaging
  src/Octokit.NET.SDK.csproj
Labels: Type: Maintenance

#22 Updates the code example with proper usings after the code shuffle
  README.md
Labels: Type: Documentation
