Repository octokit/dotnet-sdk, pull requests merged in 2024-01, with the labels that each got.

#28 feat: Adds test project with some basic tests, adds optional parameter to the RequestAdaptor
  GitHub.Octokit.sln
  Tests/Client/ClientFactoryTest.cs
  Tests/Client/RequestAdaptorTest.cs
  Tests/Tests.csproj
  Tests/xunit.runner.json
  src/Client/ClientFactory.cs
  src/Client/RequestAdapter.cs
Labels: Type: Feature

#32 docs: adds installation instructions for the package
  README.md
Labels: Type: Documentation

#34 feat: renames the nuget package and namespaces to more appropriately fit this product
  GitHub.Octokit.sln
  README.md
  Tests/Client/ClientFactoryTest.cs
  Tests/Client/RequestAdaptorTest.cs
  Tests/Tests.csproj
  src/Authentication/TokenAuthenticationProvider.cs
  src/Client/ClientFactory.cs
  src/Client/RequestAdapter.cs
  src/GitHub.Octokit.SDK.csproj
  src/Middleware/APIVersionHandler.cs
  src/Middleware/Options/APIVersionOptions.cs
  src/Middleware/Options/UserAgentOptions.cs
  src/Middleware/UserAgentHandler.cs
Labels: Type: Breaking change, Type: Feature
